#!bin/bash
while true; do

clear

figlet "          " | lolcat

sleep 2

echo -e " \033[1;32m [!]\033[0m \033[1;33m imminent danger\033[0m"   
echo ' '
echo ' '
echo ' '
echo ' '
sleep 2
echo ' '
echo -e " \033[1;32m [!]\033[0m \033[1;33m Go to left or right?(l/r)\033[0m"   
echo ' '
echo ' '
echo ' '
sleep 2
echo ' '
echo ' '
echo ' '
echo -e " \033[1;32m [Left]                  [Right]\033[0m"
echo ' '
sleep 1 
echo ' '
echo -e " \033[1;32m Heath ■■■■■■■■■■■■■ \033[0m"
sleep 1 
echo ' '
echo ' '
echo ' '
read -p ">>>>>>>>>>  " yn

case $yn in
        [lL] ) echo -e "\033[1;31m Going to left...\033[0m" ;

sleep 2

clear

sleep 2

bash file5.sss

                break;;
       [rR] ) echo -e "\033[1;31m Going to right\033[0m" ;

sleep 2

clear

sleep 1

echo -e " \033[1;31m Health ■\033[0m"

sleep 1

termux-open --view https://youtu.be/EU5Wf9jlIlg

sleep 8

bash file1

                break;;
           [+] ) echo '' ;
                exit;;
        * ) echo -e " \033[1;33m [!]\033[0m \033[5;30m Wrong Option.\033[0m"
esac

sleep 1

clear

done
