#!bin/bash
while true; do

clear

figlet "        Game " | lolcat
echo -e " \033[1;32m [!]\033[0m \033[1;33m Want Start?(y/n)\033[0m"   
echo ' '
echo ' '
echo ' '
echo ' '
sleep 2
echo ' '
echo ' '
echo ' '
echo -e " \033[1;32m [Yes]                  [No]\033[0m"
echo ' '
echo ' '
echo ' '
read -p ">>>>>>>>>>  " yn

case $yn in
        [yY] ) echo -e "\033[1;31m Starting...\033[0m" ;

sleep 2

clear

sleep 2

bash file5
                break;;
       [nN] ) echo -e "\033[1;31m 2byw5etr7s9a8q6w8t9t0g9e9w8w8w72jrot0goc9cox9jz\033[0m" ;

sleep 1

clear

sleep 2

figlet 'Its'

sleep 1

clear

figlet 'No'

sleep 1

clear

figlet 'Scape'

sleep 1

clear

sleep 2

bash file5

                break;;
          [1] )  echo '' ;
                exit;;
        * ) echo -e " \033[1;33m [!]\033[0m \033[5;30m Wrong Option.\033[0m"
esac

sleep 1

clear

done
