#!bin/bash
echo -e " \033[1;31m [t̸̵̵̷̷̶̵̛̛̲͎̘̱̟̮̙̪̩̹̗̦͔̼͈̩̭̼͉̺͇̼̹̭͙̜͌̀̏̐͐͊̀̔̐͐̇̾̀͛̓̈́̇̆̀̅͌̽̀̌̈́̐̅̎͐̒͒̿͛̃̈͑́͛̕͘̕̕̕͝͠͠͠]\033[0m \033[1;33m L\033[0m"

sleep 1

clear

echo -e " \033[1;31m [t̸͌̀̏]\033[0m \033[1;33m Le\033[0m"    

sleep 1

clear

echo -e " \033[1;31m [t̸͌̀̏]\033[0m \033[1;33m Lets\033[0m"  

sleep 1

clear

echo -e " \033[1;31m [t̸͌̀̏]\033[0m \033[1;33m Lets S\033[0m"  

sleep 1

clear

echo -e " \033[1;31m [t̸͌̀̏]\033[0m \033[1;33m Lets St\033[0m"  

sleep 1

clear

echo -e " \033[1;31m [t̸͌̀̏]\033[0m \033[1;33m Lets Sta\033[0m"  

sleep 1

clear

echo -e " \033[1;31m [t̸͌̀̏]\033[0m \033[1;33m Lets Start T\033[0m"  

sleep 1

clear

echo -e " \033[1;31m [t̸͌̀̏]\033[0m \033[1;33m Lets Start The\033[0m"  

sleep 1

clear

echo -e " \033[1;31m [t̸͌̀̏]\033[0m \033[1;33m Lets Start The\033[0m \033[1;32m REAL \033[0m"  

sleep 1

clear

echo -e " \033[1;31m [t̸͌̀̏]\033[0m \033[1;33m Lets Start The\033[0m \033[1;32m REAL GAME \033[0m"  

sleep 1

clear

moon-buggy
